### ISSUE TITLE
help watchlist.csv

### ISSUE THREAD

**Issue by degupukas** [rouyng/airspotbot#17] opened 2022-02-23 14:42 UTC
hello
excellent script
I have some questions:
where can I get support for this script?
I have installed everything but I do not check any data on twitter, I have this error:

23-Feb-22 08:37:54 - INFO: Authentication OK
23-Feb-22 08:37:54 - INFO: Twitter API created
23-Feb-22 08:37:54 - INFO: Location type set to manual
23-Feb-22 08:37:54 - INFO: Loading watchlist from ./config/watchlist.csv
23-Feb-22 08:37:54 - WARNING: Error reading row 2 from ./config/watchlist.csv, please check the watchlist file. This error is usually caused by missing columns in a row.
23-Feb-22 08:37:54 - WARNING: Error reading row 3 from ./config/watchlist.csv, please check the watchlist file. This error is usually caused by missing columns in a row.
23-Feb-22 08:37:54 - WARNING: Error reading row 4 from ./config/watchlist.csv, please check the watchlist file. This error is usually caused by missing columns in a row.
23-Feb-22 08:37:54 - WARNING: Generated 3 while reading watchlist file
23-Feb-22 08:37:54 - INFO: Added 0 entries to the watchlist
23-Feb-22 08:37:54 - INFO: Checking for aircraft via ADSBx API (endpoint: rapidapi)

any chance to help me
Thank you

**Comment by rouyng** [comment] 2022-02-23 15:44
Hello!
That error is caused by missing columns in your watchlist.csv file. The program expects each row to have five columns (for Key, Type, Mil Only, Description, Image). Even if you are not using one of the columns, there still must be a blank value there. So if you were to edit the csv in a text editor, you should see four commas on each row which demarcate the five columns. Like so:
```
Key,Type,Mil Only,Description,Image
H60,TC,N,UH-60 Black Hawk,uh60.jpg
N1234,RN,,Some aircraft,
```
In the above example, all three lines have four commas, which demarcates the five needed columns. This is required in the third line even though we do not fill in the cells for "Mil Only" or "Image".
The following will fail with the same error you observe:
```
Key,Type,Mil Only,Description,Image
N1234,RN,Some aircraft
```
Let me know if this helps you.

**Comment by rouyng** [comment] 2022-03-02 18:39
Closing this as it seems to be resolved. Feel free to open a new issue if you have other problems.

**Closed by rouyng** 2022-03-02 18:39 UTC
